name = "aitutor-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Environment variables (set these in Cloudflare dashboard or via wrangler secrets)
[vars]
ENVIRONMENT = "development"

# Production environment
[env.production]
name = "aitutor-api-prod"
vars = { ENVIRONMENT = "production" }

# Development environment
[env.development]
name = "aitutor-api-dev"
vars = { ENVIRONMENT = "development" }

# For development, you can use .env file or wrangler dev --var
# For production, use: wrangler secret put OPENAI_API_KEY
# OPENAI_API_KEY = "your-api-key"