name = "aitutor-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

# KV Namespaces
[[kv_namespaces]]
binding = "AITUTOR_KV"
id = "602f4b0aa2c84d028ff510ab23be19b5"
preview_id = "1353f14d278843499f1e390cdea59b53"

# Vectorize Indexes
[[vectorize]]
binding = "CONTENT_VECTORIZE"
index_name = "content-search"

# Queues (Producer and Consumer)
[[queues.producers]]
queue = "transcribe-queue"
binding = "TRANSCRIBE_QUEUE"

[[queues.consumers]]
queue = "transcribe-queue"
max_batch_size = 10
max_batch_timeout = 5

# Environment variables (set these in Cloudflare dashboard or via wrangler secrets)
[vars]
ENVIRONMENT = "production"

# Production environment
[env.production]
name = "aitutor-api"
vars = { ENVIRONMENT = "production" }

# Development environment
[env.development]
name = "aitutor-api-dev"
vars = { ENVIRONMENT = "development" }

# Observability settings
[observability.logs]
enabled = true