name = "aitutor-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

# KV Namespaces
[[kv_namespaces]]
binding = "aitutor_kv"
id = "602f4b0aa2c84d028ff510ab23be19b5"
preview_id = "1f17a8a9139a44659a3ea6a8e74515f9"

# Queues
[[queues.producers]]
queue = "transcribe-queue"
binding = "TRANSCRIBE_QUEUE"

[[queues.consumers]]
queue = "transcribe-queue"
max_batch_size = 10
max_batch_timeout = 5
max_retries = 3
dead_letter_queue = "transcribe-dlq"

# Environment variables (set these in Cloudflare dashboard or via wrangler secrets)
[vars]
ENVIRONMENT = "production"

# Production environment
[env.production]
name = "aitutor-api"
vars = { ENVIRONMENT = "production" }

# Development environment
[env.development]
name = "aitutor-api-dev"
vars = { ENVIRONMENT = "development" }

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[placement]
mode = "smart"

# For development, you can use .env file or wrangler dev --var
# For production, use: wrangler secret put OPENAI_API_KEY
# OPENAI_API_KEY = "your-api-key"

# Required secrets for transcription (use wrangler secret put):
# - STREAM_API_TOKEN: Cloudflare Stream API token
# - CLOUDFLARE_ACCOUNT_ID: Cloudflare account ID